/*
=====================================================================
DDL Script: Create Bronze Tables
=====================================================================

Script Purpose:
	This script create tables in the 'bronze' schema, dropping existing tables
	if they already exist.
	
	Run this script to re-define the DDL structure of 'bronze' tables
	
=====================================================================
*/


DROP TABLE IF EXISTS bronze.erp_clientes;
CREATE TABLE bronze.erp_clientes (
    plucliente INT,
    codigo INT,
    plucategoria INT,
    preferencia TEXT,
    personeria TEXT,
    nombre1 TEXT,
    nombre2 TEXT,
    apellido1 TEXT,
    apellido2 TEXT,
    apellidoc TEXT,
    nombre TEXT,
    nombrecomercial TEXT,
    contacto TEXT,
    cargocontacto TEXT, 
    noregistro TEXT,
    nit TEXT,
    giro TEXT,
    trabajo TEXT,
    trabajodireccion1 TEXT,
    trabajodireccion2 TEXT,
    trabajotelefono TEXT,
    trabajofax TEXT,
    email TEXT,
    www TEXT,
    garantia TEXT,
    observaciones TEXT,
    nei TEXT,
    cip TEXT,
    paisid INT,
    clienteidcompretencion INT,
    esgrancontribuyente TEXT,
    celular TEXT,
    fechadenacimiento DATE,
    esagenteretenciongubernamental TEXT,
    fechacreacion DATE,

    _load_ts TIMESTAMPTZ DEFAULT NOW()
);


DROP TABLE IF EXISTS bronze.erp_divisiones;
CREATE TABLE bronze.erp_divisiones (
	pludivision INT,
	pluempresa INT,
	codigo TEXT,
	nombre TEXT, 
	direccion1 TEXT,
	direccion2 TEXT,
	ciudad TEXT,
	departamento TEXT,
	telefono TEXT,
	fax TEXT,
	fiscal TEXT,
	diasminimo INT,
	diasmaximo INT,
	enviar TEXT,
	recibir TEXT,
	regionid INT,
	factorcomprasplaza NUMERIC(13,2),

	_load_ts TIMESTAMPTZ DEFAULT NOW()
	
);

DROP TABLE IF EXISTS bronze.erp_usuarios;
CREATE TABLE bronze.erp_usuarios(
    usuarioid INT,
	codigo INT,
	nombre TEXT,
	nombrecompleto TEXT,
	clave TEXT,
	plugestor INT,
	cargo TEXT,
	habilitado TEXT

	_load_ts TIMESTAMPTZ DEFAULT NOW()
);


DROP TABLE IF EXISTS bronze.erp_gestores;
CREATE TABLE bronze.erp_gestores (
    plugestor INT,
	codigo INT,
	nombre TEXT,
	habilitado TEXT,

	_load_ts TIMESTAMPTZ DEFAULT NOW()
);

DROP TABLE IF EXISTS bronze.erp_inventario;
CREATE TABLE bronze.erp_inventario (
	pluempresa INT,
	pludivision INT,
	pluproducto INT,
	item INT,
	fecha DATE,
	tipo TEXT,
	referencia TEXT,
	nombre TEXT,
	entrada INT,
	salida INT,
	existencia INT,
	debe NUMERIC(13,6),
	haber NUMERIC(13,6),
	saldo NUMERIC(13,6),
	costopromedio NUMERIC(13,6),
	unitario NUMERIC(13,6),
	obsoleto TEXT,
	clasificacionobsoleto TEXT,
	costopromempresa NUMERIC(13,4),
	referenciaautorizacion TEXT,
	referenciaserie TEXT,
	compraretaceo TEXT,
	docaduana TEXT,
	paisproveedor TEXT,
	documentoid  INT,
	itemdocumento INT,
	
    _load_ts TIMESTAMPTZ DEFAULT NOW()
);

DROP TABLE IF EXISTS bronze.erp_empresas;
CREATE TABLE bronze.erp_empresas (
    empresaid INT,
    codigo TEXT,
    nombre TEXT,
    direccion1 TEXT,
    direccion2 TEXT,
    ciudad TEXT,
    departamento TEXT,
    telefono TEXT,
    fax TEXT,
    noregistro TEXT,
    nit TEXT,
    giro TEXT,
    fechainicial DATE,
    fechafinal DATE,
    piva NUMERIC(13,2),
    email TEXT,
    monedaid INT,
    paisid INT,
    gerentegeneral TEXT,
    auditor TEXT,
    contador TEXT,
    estadoresultados TEXT,
    validanit TEXT,
    validanei TEXT,
    admiteconsumidorfinal TEXT,
    admiteclientecero TEXT,
    fijariva TEXT,
    modificarnombretposcredito TEXT,
    preciosconiva TEXT,
    intervclasifventascontado INT,
    intervclasifventascredito INT,
    intervclasifpagoscredito INT,
    contratosclasifpagofinanciado INT,
    aproximarcentavosplanilla TEXT,
    precioaplicadoid INT,
    retenerrentadecr TEXT,
    minimoenmayoreo NUMERIC(13,2),
    usarcostopromempresa TEXT,
    esgrancontribuyente TEXT,
    exigirdocidentidad TEXT,
    validezcotizacion INT,
    tiponumeracionpartidas TEXT,
    abonosfingeneranfc TEXT,
    noesagentepercepcion TEXT,
    retenerivadecr TEXT,
    validanoregistro TEXT,
    corteusacorrelativotk TEXT,

    _load_ts TIMESTAMPTZ DEFAULT NOW()
);

DROP TABLE IF EXISTS bronze.erp_docclientesm;
CREATE TABLE bronze.erp_docclientesm (
    pludoccliente INT,
    pluusuario INT,
    plugestor INT,
    pluempresa INT,
    pludivision INT,
    tipo TEXT,
    condiciones TEXT,
    tipoprecio TEXT,
    codigo INT,
    fecha DATE,
    hora TIME,
    plucliente INT,
    referencia TEXT,
    ordencompra TEXT,
    ordentaller TEXT,
    nombre TEXT,
    direccion1 TEXT,
    direccion2 TEXT,
    ciudad TEXT,
    departamento TEXT,
    noregistro TEXT,
    giro TEXT,
    observaciones TEXT,
    subtotalexento NUMERIC(13,4),
    subtotalgravado NUMERIC(13,4),
    pdescuentoexento NUMERIC(13,2),
    pdescuentogravado NUMERIC(13,2),
    descuentoexento NUMERIC(13,4),
    descuentogravado NUMERIC(13,4),
    rebajaexento NUMERIC(13,4),
    rebajagravado NUMERIC(13,4),
    sumaexento NUMERIC(13,4),
    sumagravado NUMERIC(13,4),
    iva NUMERIC(13,4),
    total NUMERIC(13,2),
    post TEXT,
    cerrado TEXT,
    impreso TEXT,
    piva NUMERIC(13,2),
    nei TEXT,
    autorizadorid INT,
    clasedocumentoid INT,
    monedaid INT,
    factorcambio NUMERIC(13,6),
    reimpresiones INT,
    creditos TEXT,
    tipoaplicacion TEXT,
    tipopagoid INT,
    emisorid INT,
    nodocumento TEXT,
    nombreendocumento TEXT,
    comision NUMERIC(13,2),
    referencia1 TEXT,
    referenciadevolucion TEXT,
    tipooperacionid INT,
    efectivo NUMERIC(13,2),
    vuelto NUMERIC(13,2),
    descuentogravadoconiva NUMERIC(13,4),
    rebajagravadoconiva NUMERIC(13,4),
    clienteexento TEXT,
    liberado TEXT,
    documentounico TEXT,
    direccionnombre TEXT,
    tiposervicioid INT,
    documentoaduanero TEXT,
    entregarcupones TEXT,
    cupones NUMERIC(13,2),
    doccomision TEXT,
    totalcomision NUMERIC(13,2),
    retencioniva NUMERIC(13,4),
    retencionrenta NUMERIC(13,2),
    nit TEXT,
    docidentidad TEXT,
    percibiriva TEXT,
    ivapercibido NUMERIC(13,4),
    clienteretendraiva TEXT,
    nocomprobanteretencion TEXT,
    cortex INT,
    autorizacion TEXT,
    serie TEXT,
    autorizaciondocunico TEXT,
    seriedocunico TEXT,
    referenciadevolucionid INT,
    nombreencupon TEXT,
    referenciacotizacion TEXT,
    referenciacotizacionid INT,
    estacionid INT,
    referenciacontratoid INT,
    totalnosujetos NUMERIC(13,4),
    comisionpagada TEXT,
    cuponaplicado TEXT,

    _load_ts TIMESTAMPTZ DEFAULT NOW()
);

DROP TABLE IF EXISTS bronze.erp_docclientesd;
CREATE TABLE bronze.erp_docclientesd (
    pludoccliente INT,
    pluempresa INT,
    pludivision INT,
    item INT,
    cantidad INT,
    pluproducto INT,
    unitario NUMERIC(13,4),
    total NUMERIC(13,4),
    esexento TEXT,
    autorizadorid INT,
    descuento NUMERIC(13,2),
    tipoprecio TEXT,
    unitarioconiva NUMERIC(13,4),
    totalconiva NUMERIC(13,4),
    cupones NUMERIC(13,2),
    comision NUMERIC(13,2),
    costopromempresa NUMERIC(13,4),
    armardesarmar TEXT,

    _load_ts TIMESTAMPTZ DEFAULT NOW()
);

DROP TABLE IF EXISTS bronze.erp_productos;
CREATE TABLE bronze.erp_productos (
    pluproducto INT,
    pluempresa INT,
    plugrupo INT,
    nobasico TEXT,
    bc TEXT,
    plufabricante INT,
    nooriginal TEXT,
    unidad TEXT,
    descripcion TEXT,
    nauca TEXT,
    lista NUMERIC(13,4),
    mayoreo NUMERIC(13,4),
    oferta NUMERIC(13,4),
    promocion NUMERIC(13,4),
    minimo INT,
    maximo INT,
    puntopedido INT,
    observaciones TEXT,
    clasificacion TEXT,
    esmayoreo TEXT,
    exento TEXT,
    diastransito INT,
    habilitado TEXT,
    fechacreacion DATE,
    diasgracia INT,
    clasificacionobsoletoid INT,
    fechaestadistica DATE,
    diasestadistica INT,
    diasnoventa INT,
    clasificacionunidadesid INT,
    unidadesanuales INT,
    acumuladounidades NUMERIC(13,2),
    ventasperdidasanuales INT,
    fma INT,
    pendientes INT,
    cantidaddistribucion INT,
    multiploventa INT,
    resurtir TEXT,
    parametroconteo INT,
    tiempoentregaindividual INT,
    tiempoentregaembarque INT,
    desviaciontipica NUMERIC(13,2),
    pedidoautomatico TEXT,
    existenciaforzada INT,
    listaconiva NUMERIC(13,4),
    mayoreoconiva NUMERIC(13,4),
    ofertaconiva NUMERIC(13,4),
    promocionconiva NUMERIC(13,4),
    tipo TEXT,
    multiplomayoreo INT,
    rompermultiplos TEXT,
    costopromempresa NUMERIC(13,4),
    rotacionanual NUMERIC(13,2),
    ingresosanuales NUMERIC(13,2),
    safetystock INT,
    nopedir TEXT,
    productoidmultiplo INT,
    esunidadminima TEXT,
    multiplodeunidadminima NUMERIC(13,6),
    esunidadestadistica TEXT,
    escalaslistahabilitado TEXT,
    descargarventasfichamiembros TEXT,
    noesunidadmanejo TEXT,
    manejaseries TEXT,
    serieeslote TEXT,
    tiposerieid INT,

    _load_ts TIMESTAMPTZ DEFAULT NOW()
);

